const text = {
  login: "ログイン",
  logout: "ログアウト",
  email: "メール",
  password: "パスワード",
  menu: "メニュー",
  display: "表示",
  createMenu: "メニューを作成",
  create: "作成",
  name: "名前",
  price: "価格",
  avatar: "アバター",
  description: "説明",
  category: "カテゴリー",
  selectCategory: "カテゴリーを選択",
  menuSetting: "メニュー設定",
  user: "ユーザー",
  order: "注文",
  yen: "¥ ",
  payment: "会計",
  selectOrderMessage: "注文を選択してください",
  noData: "データがありません",
  subTotal: "小計",
  tax: "税",
  total: "合計",
  unpaid: "未払い",
  paid: "支払い済み",
  deposit: "預り金",
  change: "お釣り",
  depositError: "預り金が不足しています",
  orderSuccess: "注文が完了しました",
  orderFailed: "注文に失敗しました",
  paymentSuccess: "会計が完了しました",
  paymentFailed: "会計に失敗しました",
  createMenuSuccess: "メニューが作成されました",
  uploadAvatar: "アバターをアップロード",
};

export default text;
