# query Orders {
#   orders {
#     id
#     createdAt
#     total
#     # orderItems {
#     #   menu {
#     #     avatar
#     #     price
#     #   }
#     # }
#   }
# }

query OrderDetail($id: Int!) {
  orders_by_pk(id: $id) {
    id
    total
    createdAt
    status
    deposit
    orderItems {
      id
      quantity
      menu {
        avatar
        name
        price
      }
    }
  }
}
