query GetUnpaidTables {
  getUnpaidTables {
    timestamp
    statusCode
    errorMessage
    errorCode
    data {
      id
      name
      openAt
      total
    }
  }
}


query GetUnpaidOrderItemsByTableId($tableId: Int!) {
  orderItems(where: {order: {tableId: {_eq: $tableId}}, _and: {order: {status: {_eq: "PENDING"}}}}) {
    id
    price
    quantity
    menu {
      avatar
      name
    }
  }
}
