mutation CreatePayment($createPaymentInput: CreatePaymentInput = {tableId: 10}) {
  createPayment(createPaymentInput: $createPaymentInput) {
    timestamp
    statusCode
    errorMessage
    errorCode
  }
}
